### ISSUE TITLE
thread 'main' has overflowed its stack

### ISSUE THREAD

**Issue by danielniccoli** [fgardt/factorio-scanner#1]
https://github.com/fgardt/factorio-scanner/blob/7126509d0bf93dc97caff6dc53f73e7cfe35819f/scanner/src/main.rs#L73

throws a `thread 'main' has overflowed its stack`

**Comment by fgardt** [comment]
Interesting. What dump did you use to trigger this?

**Comment by danielniccoli** [comment]
[data-raw-dump.zip](https://github.com/fgardt/factorio-scanner/files/13232314/data-raw-dump.zip)

**Comment by fgardt** [comment]
ok I have not tested anything outside of linux (nixOS in my case) so far

**Comment by fgardt** [comment]
that dump is actually a bit shorter than the one I am using.. hmm

I wonder if minimizing them before parsing could help?

**Comment by danielniccoli** [comment]
It's the dump from `--dump-data`. Minified causes the same error. Does my dump work for you?

**Comment by fgardt** [comment]
not tested it yet, I'll push a change soon that changes thins to be actually read from files instead of hardcoded into the executable

**Comment by fgardt** [comment]
I tested it on my machine with the dump you provided, works perfectly fine on my machine.

It could be that some prototype struct is a bit too large for windows..

**Comment by fgardt** [comment]
@danielniccoli could you try again now that #3 is merged? you can just specify the files you want to use with cli args

**Comment by fgardt** [comment]
Just tested it in my windows VM and the current version works fine so #3 might have fixed it

**Comment by danielniccoli** [comment]
#3 is a confirmed fix.
