### ISSUE TITLE
tile rendering

### ISSUE THREAD

**Issue by Jopo-JP** [fgardt/factorio-scanner#142]
Just an addiontal option, to allow rendering of tiles on the ground, like landfill, concrete and so on.

Great work!

**Comment by fgardt** [comment]
Tile rendering is already implemented. The current implementation is just very basic tho so it can still be improved.

**Comment by fgardt** [comment]
> in the current release it isnÄt included yet. at the moment it is rendring the blueprint just like in the game simply flat.

yeah the "current" release is quite old at this point :D
