### ISSUE TITLE
thread 'main' has overflowed its stack

### ISSUE THREAD

**Issue by danielniccoli** [fgardt/factorio-scanner#7]
```
PS> .\target\debug\scanner.exe --dump "C:\Users\Daniel\AppData\Roaming\Factorio\script-output\data-raw-dump.json" --out c:\temp\out.png --factorio "C:\Program Files (x86)\Steam\steamapps\common\Factorio" --blueprint "C:\Users\Daniel\AppData\Roaming\Factorio\script-output\blueprint.txt"
loaded BP

thread 'main' has overflowed its stack
```

[input.zip](https://github.com/fgardt/factorio-scanner/files/13245788/input.zip)

**Comment by fgardt** [comment]
hmm so #1 was not actually fixed by #3?

**Comment by fgardt** [comment]
ok I can reproduce it in my windows VM!

interestingly enough it does not happen when compiling in release mode (which I did since the start of the project when running it was pretty slow even in release but its been better after some optimizations so I should switch to debug building again 😄)

**Comment by fgardt** [comment]
#8 should fix this

**Comment by danielniccoli** [comment]
Fixed
